// <auto-generated />
using System;
using BookStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore.Data
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250713112749_InitialCreateWithEcommerceEntities")]
    partial class InitialCreateWithEcommerceEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookAuthors", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthors");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 2
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 3
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 4
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 5
                        });
                });

            modelBuilder.Entity("BookStore.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1965, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "J.K. Rowling"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1948, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "George R.R. Martin"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1947, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Stephen King"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1890, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Agatha Christie"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1899, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ernest Hemingway"
                        });
                });

            modelBuilder.Entity("BookStore.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Publisher")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The first book in the Harry Potter series",
                            Genre = "Fantasy",
                            Language = "Persian",
                            Price = 24.99m,
                            PublishDate = new DateTime(1997, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Cheshmeh",
                            StockQuantity = 50,
                            Title = "Harry Potter and the Philosopher's Stone",
                            UpdatedAt = new DateTime(2023, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 3, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The first book in A Song of Ice and Fire",
                            Genre = "Fantasy",
                            Language = "Persian",
                            Price = 29.99m,
                            PublishDate = new DateTime(1996, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Ava",
                            StockQuantity = 35,
                            Title = "A Game of Thrones",
                            UpdatedAt = new DateTime(2023, 3, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A horror novel about a haunted hotel",
                            Genre = "Horror",
                            Language = "English",
                            Price = 19.99m,
                            PublishDate = new DateTime(1977, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Doubleday",
                            StockQuantity = 25,
                            Title = "The Shining",
                            UpdatedAt = new DateTime(2023, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 4, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic murder mystery by Agatha Christie.",
                            Genre = "Mystery",
                            Language = "English",
                            Price = 12.99m,
                            PublishDate = new DateTime(1939, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Collins Crime Club",
                            StockQuantity = 40,
                            Title = "And Then There Were None",
                            UpdatedAt = new DateTime(2023, 4, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 5, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A novella by Ernest Hemingway about an aging Cuban fisherman.",
                            Genre = "Fiction",
                            Language = "English",
                            Price = 12.99m,
                            PublishDate = new DateTime(1952, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Scribner",
                            StockQuantity = 30,
                            Title = "The Old Man and the Sea",
                            UpdatedAt = new DateTime(2023, 5, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BookStore.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Admin St, Admin City, AC 12345",
                            CreatedAt = new DateTime(2023, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@bookstore.com",
                            FirstName = "Admin",
                            LastName = "User",
                            PhoneNumber = "+1234567890",
                            UpdatedAt = new DateTime(2023, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Main St, Anytown, AT 54321",
                            CreatedAt = new DateTime(2023, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@email.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = "+1234567891",
                            UpdatedAt = new DateTime(2023, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Oak Ave, Somewhere, SW 67890",
                            CreatedAt = new DateTime(2023, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1992, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@email.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PhoneNumber = "+1234567892",
                            UpdatedAt = new DateTime(2023, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Address = "999 Guest St, Guest City, GC 99999",
                            CreatedAt = new DateTime(2023, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "guest@email.com",
                            FirstName = "Guest",
                            LastName = "Customer",
                            PhoneNumber = "+1234567893",
                            UpdatedAt = new DateTime(2023, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Address = "101 Pine Ln, Forest Town, FT 11111",
                            CreatedAt = new DateTime(2023, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1988, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob.wilson@email.com",
                            FirstName = "Bob",
                            LastName = "Wilson",
                            PhoneNumber = "+1234567894",
                            UpdatedAt = new DateTime(2023, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 4
                        });
                });

            modelBuilder.Entity("BookStore.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ShippingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShippingMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 7, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 2,
                            DiscountAmount = 0m,
                            Notes = "First order from John Doe",
                            OrderDate = new DateTime(2024, 7, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "Credit Card",
                            PaymentStatus = 1,
                            ShippingAddress = "456 Main St, Anytown, AT 54321",
                            ShippingAmount = 5.99m,
                            ShippingMethod = "Standard",
                            Status = 3,
                            Subtotal = 44.98m,
                            TaxAmount = 4.50m,
                            TotalAmount = 55.47m,
                            TransactionId = "TXN_001_2024",
                            UpdatedAt = new DateTime(2024, 7, 12, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 7, 10, 14, 30, 0, 0, DateTimeKind.Utc),
                            CustomerId = 3,
                            DiscountAmount = 0m,
                            Notes = "Express shipping requested",
                            OrderDate = new DateTime(2024, 7, 10, 14, 30, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "PayPal",
                            PaymentStatus = 1,
                            ShippingAddress = "789 Oak Ave, Somewhere, SW 67890",
                            ShippingAmount = 5.99m,
                            ShippingMethod = "Express",
                            Status = 2,
                            Subtotal = 32.98m,
                            TaxAmount = 3.30m,
                            TotalAmount = 42.27m,
                            TransactionId = "TXN_002_2024",
                            UpdatedAt = new DateTime(2024, 7, 12, 14, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 7, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 4,
                            DiscountAmount = 0m,
                            Notes = "Guest order",
                            OrderDate = new DateTime(2024, 7, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "Credit Card",
                            PaymentStatus = 0,
                            ShippingAddress = "999 Guest St, Guest City, GC 99999",
                            ShippingAmount = 5.99m,
                            ShippingMethod = "Standard",
                            Status = 0,
                            Subtotal = 19.99m,
                            TaxAmount = 2.00m,
                            TotalAmount = 27.98m,
                            UpdatedAt = new DateTime(2024, 7, 12, 9, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BookStore.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            DiscountAmount = 0m,
                            OrderId = 1,
                            Quantity = 1,
                            Subtotal = 24.99m,
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            Id = 2,
                            BookId = 3,
                            DiscountAmount = 0m,
                            OrderId = 1,
                            Quantity = 1,
                            Subtotal = 19.99m,
                            UnitPrice = 19.99m
                        },
                        new
                        {
                            Id = 3,
                            BookId = 2,
                            DiscountAmount = 0m,
                            OrderId = 2,
                            Quantity = 1,
                            Subtotal = 29.99m,
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            Id = 4,
                            BookId = 5,
                            DiscountAmount = 0m,
                            OrderId = 2,
                            Quantity = 1,
                            Subtotal = 12.99m,
                            UnitPrice = 12.99m
                        },
                        new
                        {
                            Id = 5,
                            BookId = 3,
                            DiscountAmount = 0m,
                            OrderId = 3,
                            Quantity = 1,
                            Subtotal = 19.99m,
                            UnitPrice = 19.99m
                        });
                });

            modelBuilder.Entity("BookStore.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            Comment = "Fantastic book! A perfect introduction to the magical world.",
                            CreatedAt = new DateTime(2024, 6, 10, 15, 30, 0, 0, DateTimeKind.Utc),
                            Rating = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            Comment = "Great but too violent for my taste. Excellent world-building though.",
                            CreatedAt = new DateTime(2024, 6, 15, 11, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            BookId = 3,
                            Comment = "Scared me to death! Masterpiece of horror literature.",
                            CreatedAt = new DateTime(2024, 6, 20, 9, 45, 0, 0, DateTimeKind.Utc),
                            Rating = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            BookId = 4,
                            Comment = "Classic mystery novel. Poirot is brilliant as always.",
                            CreatedAt = new DateTime(2024, 6, 25, 14, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            BookId = 5,
                            Comment = "Good story but a bit slow-paced for my liking.",
                            CreatedAt = new DateTime(2024, 7, 1, 10, 20, 0, 0, DateTimeKind.Utc),
                            Rating = 3,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("BookStore.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "hashed_admin_password_123",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "hashed_john_password_123",
                            Username = "john_doe"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = "hashed_jane_password_123",
                            Username = "jane_smith"
                        },
                        new
                        {
                            Id = 4,
                            PasswordHash = "hashed_bob_password_123",
                            Username = "bob_wilson"
                        });
                });

            modelBuilder.Entity("BookAuthors", b =>
                {
                    b.HasOne("BookStore.Models.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookStore.Models.Customer", b =>
                {
                    b.HasOne("BookStore.Models.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("BookStore.Models.Customer", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookStore.Models.Order", b =>
                {
                    b.HasOne("BookStore.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookStore.Models.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BookStore.Models.OrderItem", b =>
                {
                    b.HasOne("BookStore.Models.Book", "Book")
                        .WithMany("OrderItems")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookStore.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BookStore.Models.Review", b =>
                {
                    b.HasOne("BookStore.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.Models.User", "User")
                        .WithMany("Review")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookStore.Models.Book", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BookStore.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BookStore.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BookStore.Models.User", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Orders");

                    b.Navigation("Review");
                });
#pragma warning restore 612, 618
        }
    }
}
